docs/index.md
integration/integration_test.go
internal/provider/provider.go

It was incorrectly linked to 2.13.0.

fix: fix minimum coder version warning

---

internal/provider/group_resource.go
internal/provider/template_resource.go
internal/provider/user_resource.go

The Terraform provider plugin framework generates a lot of noise on `debug` and `trace`. 
Given how few there are, the existing log calls aren't really traces - it's more reasonable for these logs to be on `info`. 
This also includes streaming the logs from the provisioner to `info`, which would be necessary if you wanted to know why a template couldn't be built.

chore: tflog trace -> info

---

docs/resources/template.md
examples/resources/coderd_template/resource.tf

Otherwise it might not be immediately obvious how to make a private template.

docs: fix missing required attribute in example

---

docs/resources/group.md
docs/resources/template.md
docs/resources/user.md
internal/provider/group_resource.go
internal/provider/group_resource_test.go
internal/provider/template_resource.go
internal/provider/template_resource_test.go
internal/provider/user_resource.go
internal/provider/user_resource_test.go

Previously, user, group and template resources could only be imported via their UUIDs. The `coder/coder` frontend doesn't expose these UUIDs to the user, so we should provide an alternative, more user-friendly way to import resources.
User resources: ID or username, since usernames must be unique, even across multiple orgs.
Template resources: ID or `<organization-name>/<template-name>`
Group resources: ID or `<organization-name/<group-name>`

chore: support importing resources by fully qualified names

---

internal/provider/group_resource.go
internal/provider/template_resource.go
internal/provider/user_resource.go
internal/provider/util.go

Unfortunately, `coderd` validation errors don't return the reason why the validation failed, leading to confusing (almost useless) error messages when creating templates, groups or users with invalid names via the provider. 
The changes on `coderd/httpapi` to resolve this are non-trivial, as the [struct validation library](https://pkg.go.dev/github.com/go-playground/validator/v10) we use doesn't appear to support attaching an error reason to a field validator function.
Instead, we'll translate the string validation functions and regex from `coderd/httpapi/name.go`.

chore: validate fields as per coderd

---

integration/integration.go

Our provider acceptance tests caught a very minor bug in `dbmem`, causing all CI to fail against the latest Coder image. 
Since nobody runs Coder using `dbmem`, It'd be better to test that the provider runs against the DB that people actually use. 
Running the acceptance tests on my dogfood workspace took ~140 seconds, up from ~80 using `dbmem` - but I think it's a fine tradeoff, and also means we don't need to modify our test suite to workaround the bug.
Treating this as a hotfix and merging.

fix: use postgres for tests instead of dbmem

---

docs/data-sources/group.md
docs/data-sources/user.md
docs/resources/group.md
docs/resources/user.md
docs/resources/workspace_proxy.md
internal/provider/group_data_source.go
internal/provider/group_resource.go
internal/provider/user_data_source.go
internal/provider/user_resource.go
internal/provider/workspace_proxy_resource.go

- Ensure consistent usage of backticks for inline code.
- Fix a typo in the `icon` attribute description.

Improve markdown for attribute descriptions

---

internal/provider/template_resource.go
internal/provider/template_resource_test.go

The provider currently does not remove users or groups from template ACL when applying a config.
This was unfortunately missed by tests, but caught by our use of the provider to manage our dogfood template.
Merely omitting a ACL item in a `coderd` API request is not enough to delete it, the role string must be set to an empty string. 
ACL items will now be deleted from the template when they are removed from the config and applied.

fix: correctly patch template acl

---

go.mod
go.sum

I don't totally understand why CI tests passed (as goreleaser did not), but upgrading our codersdk `v2.15.0` introduced `coderdtest` as a dependency, when we want to avoid all the dependencies it requires, i.e. tailscale & gvisor, and the go mod replace directives for them.
`codersdk` `v2.14.2` works fine against a `v2.15.0` deployment, so this is safe. When `v2.15.0` gets patched we'll upgrade once again.
Related: https://github.com/coder/coder/pull/14633
Treating as hotfix & merging.

fix: downgrade coder v2.15.0 -> 2.14.2

---

internal/provider/template_data_source_test.go
internal/provider/template_resource.go

Closes #92.
Currently, the logs are only streamed to tflog and not dumped on failure. Now, if the provisioner build fails for any reason, the logs will be included in the final Terraform error, which, unlike tflog, is always shown.
```
│ Error: Provisioner Error
│ 
│   with coderd_template.sample,
│   on main.tf line 24, in resource "coderd_template" "sample":
│   24: resource "coderd_template" "sample" {
│ 
│ failed to wait for job: provisioner job did not succeed: failed (template
│ import provision for start: terraform plan: exit status 1)
│ 2024-09-12 03:14:05.029Z Initializing the backend...
│ 2024-09-12 03:14:05.029Z Initializing provider plugins...
│ 2024-09-12 03:14:05.029Z - Finding latest version of hashicorp/local...
│ 2024-09-12 03:14:05.687Z - Installing hashicorp/local …
```

chore: dump provisioner logs on error

---

internal/provider/group_data_source.go
internal/provider/group_resource.go
internal/provider/license_resource.go
internal/provider/organization_data_source.go
internal/provider/template_data_source.go
internal/provider/template_resource.go
internal/provider/user_data_source.go
internal/provider/user_resource.go
internal/provider/util.go
internal/provider/workspace_proxy_resource.go

Closes #100.
Hashicorp's own providers only do this deletion if the resource can't be found during `Read`, and not during `Update`, so we'll do the same.

fix: delete resources & data sources if not found

---

docs/resources/template.md
internal/provider/template_resource.go
internal/provider/template_resource_test.go

This is a somewhat hacky, temporary, solution to #108.
Prior to Coder `v2.15.0` (via https://github.com/coder/coder/pull/14366), it was not possible to set the max port sharing level when the template was created. To retain compatibility between the template resource and older, supported, versions of Coder, the provider will make a `PATCH` request immediately after creating the template to set the max port sharing level.
When we no longer support versions of Coder prior to `v2.15.0`, we'll remove the redundant update request.

feat: add template max port sharing level attribute

---

docs/resources/template.md
examples/resources/coderd_template/resource.tf

The template example that used a Git commit hash in the name of each version referenced a Terraform variable that's only populated when using Terraform Cloud. There's not a great universal way to populate the variable within Terraform, so we'll instead mention two ways one could otherwise set it.

docs: replace example that requires TFC

---

docs/resources/group.md
docs/resources/template.md
docs/resources/user.md
examples/resources/coderd_group/import.sh
examples/resources/coderd_template/import.sh
examples/resources/coderd_user/import.sh
internal/provider/group_resource.go
internal/provider/template_resource.go
internal/provider/user_resource.go

Closes #117.
Replaces the sentence on imports at the top of each resource with an entire section at the bottom, like many other providers.
Appending extra content to the auto-gen'd docs is a pain (it gets overridden by go gen) so we just do some sneaky codeblock escaping within the shell files and it works nicely.

docs: add import examples

---

internal/provider/template_resource.go

This was unfortunately missed. There's not a great way to assert that the provisioner tags are even being included in the request. They're stored in the database for each template version, but we don't expose a way to retrieve them and verify they were sent.
Treating as hotfix and merging.

fix: include provisioner tags when creating template version

---

internal/provider/group_data_source_test.go
internal/provider/group_resource_test.go
internal/provider/organization_data_source_test.go
internal/provider/template_data_source_test.go
internal/provider/template_resource.go
internal/provider/template_resource_test.go
internal/provider/user_data_source_test.go
internal/provider/user_resource_test.go
internal/provider/util.go
internal/provider/workspace_proxy_resource_test.go

we already import coder/coder into this repo, and it's nice to have one name for things across code bases

chore: replace `PtrTo` with `ptr.Ref`

---

.github/workflows/test.yml

Discovered in #141 that CI could pass even when `make gen` could produce a new file.

ci: check for unstaged files correctly during gen

---

internal/provider/user_data_source_test.go
internal/provider/uuid.go
internal/provider/uuid_internal_test.go

When I first implemented the UUID Terraform type, I followed the example from `terraform-provider-aws` for durations: [Source](https://sourcegraph.com/github.com/hashicorp/terraform-provider-aws/-/blob/internal/framework/types/duration.go). This example doesn't quite make sense, or at the least isn't applicable to our use-case, and since it was used as a base for our custom data type, resulted in UUIDs not being validated when written as strings in a configuration.
i.e. This function is called by the plugin SDK, when reading the config.
```
func (t durationType) ValueFromString(_ context.Context, in types.String) (basetypes.StringValuable, diag.Diagnostics) {
[...]
valueString := in.ValueString()
if _, err := time.ParseDuration(valueString); err != nil {
return DurationUnknown(), diags // …
```

fix: mark invalid UUIDs as known

---

README.md
docs/resources/organization.md
examples/resources/coderd_organization/import.sh
internal/provider/organization_resource.go

Output can be previewed by pasting the markdown into https://registry.terraform.io/tools/doc-preview

docs: update org resource

---

docs/index.md
examples/provider/provider.tf
integration/integration.go
internal/provider/provider.go

Closes #159.
This updates the documentation to include the access URL scheme in the example, matching the coder.com docs.
It also implicitly adds the scheme to the provided access URL if not present, only prepending `http://` if the access URL is localhost. This is the same behaviour as `coder login`.

docs: add URL scheme to example

---

.github/workflows/test.yml
.golangci.yml
Makefile

CI is broken right now because of some breaking change with golangci. Gotta update the config to fix things.

chore: fix golangci config

---

internal/provider/organization_resource.go
internal/provider/organization_resource_test.go

I picked up on this reviewing #182, but it's a mistake I made when reviewing the resource originally 😓 
There's a minor inconsistency between display names on orgs and some other resources with display names on `coderd`. i.e. for organizations:
```
if req.DisplayName == "" {
req.DisplayName = req.Name
}
```
For some other resources, e.g. users & groups, an empty string display name is retained, and the CLI/Web UI just shows the actual name if the display name is empty. For those, it's okay to have an empty string default in the provider.

fix: use server computed org display name

---

internal/provider/template_resource.go
internal/provider/template_resource_test.go

Closes #188.
For context, the `MaxPortShareLevel` template metadata value was not present on the `coderd` create template request prior to 2.15. As such, during template creation we need to send an update request for backwards compatibility (though we could probably remove this soon), see #110.
Whilst we don't send this update request is the attribute is omitted on the resource, we were sending a spurious update request if the value was explicitly configured to the default value ('owner' for enterprise+, 'public' otherwise). This was causing the error in the linked issue. An example is seen in the newly added test. 
The fix is to just not send that update request if the configured value is:
- Unknown
- Equal to the value on the newly created template.
note: I'd recommend hiding the …

fix: avoid sending template metadata update if `max_port_share_level` is default

---

internal/provider/user_resource.go
internal/provider/user_resource_test.go
internal/provider/util.go

Closes #208.
Querying `api/v2/users/{ID}` returns a valid response for deleted users, as deleted users in `coderd` are merely tombstoned. To handle this, we perform an additional query by username. If the user has been deleted, the username will be available, or belong to a user with a different ID, in which case we can mark the user resource as deleted.
Also has the `isNotFound` check include the specific response for when a user does not exist:
```
sdkErr.StatusCode() == http.StatusBadRequest && strings.Contains(sdkErr.Message, "must be an existing uuid or username")
```

fix: handle user deletion config drift

---

docs/resources/user.md
integration/integration.go
internal/provider/user_resource.go
internal/provider/user_resource_test.go

A customer ran into an issue when creating an OIDC user while role sync was enabled on the deployment:
```
Error: 'User Role Field' is set in the OIDC configuration. All role changes must come from the oidc identity provider. 
```
This is because we always call `UpdateUserRoles` on `Create` and `Update`.
OIDC User roles cannot be managed via the API if role sync is used, as the API always returns an error on any role update request. 
With this PR, `roles` can now be set to `null` in the config, whereby the Terraform provider will not attempt to read or update the user's roles under any circumstances. This prevents config drift when roles are set via Role Sync.

fix: support unmanaged roles on user resource
